# Generated by Django 5.2.4 on 2025-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('skills_covered', models.JSONField(default=list, help_text='Skills taught in this course')),
                ('course_description', models.TextField()),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('job_description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
