# Generated by Django 5.2.4 on 2025-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temp_password_used',
            field=models.BooleanField(default=True),
        ),
    ]
