# Generated by Django 5.2.4 on 2025-07-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_temp_password_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_temp_password_used',
            field=models.BooleanField(default=False),
        ),
    ]
